[background]
name = "Night Sky"

# In our parallax background/nightsky, z=100 means it is as far as possible
# and the least sensitive to height changes

[[layer]]
texture = "textures/background/nightsky/nightsky_1.png"
z = 40

[[layer]]
texture = "textures/background/nightsky/nightsky_3.png"
z = 60

[[layer]]
texture = "textures/background/nightsky/nightsky_4.png"
z = 75

[[layer]]
texture = "textures/background/nightsky/nightsky_5.png"
z = 80

[[layer]]
texture = "textures/background/nightsky/nightsky_6.png"
z = 85

[[layer]]
texture = "textures/background/nightsky/nightsky_7.png"
z = 85
