[character]
name = "Raptr"
mass_kg = 80.0
walk_speed_kmh = 14.0
run_speed_kmh = 24.0
jump_vel_ms = 4.5
jumps_allowed = 2
jump_perfect_scale = 1.50
fast_fall_scale = 2.5
dash_scale = 1.25
dash_speed_kmh = 40.0
dash_length_msec = 150

[sprite]
path = "textures/raptor.json"
scale = 1.0

[[sounds]]
animation = "Walk"
wav = "sound/characters/raptr/walk.wav"
loop = true
frame = -1

[[sounds]]
animation = "Run"
wav = "sound/characters/raptr/run.wav"
loop = true
frame = -1

#[[sounds]]
#animation = "Dash"
#wav = "sound/characters/raptr/dash.wav"
#loop = true

#[[sounds]]
#animation = "Jump"
#wav = "sound/characters/raptr/jump.wav"
#loop = false
