[character]
name = "Raptr"
walk_speed = 100
run_speed = 300
jump_vel = 550
jumps_allowed = 2
jump_perfect_scale = 1.50
fast_fall_scale = 2.5
dash_scale = 1.25
dash_speed = 650
dash_length_ms = 250

[sprite]
path = "textures/raptor.json"
scale = 1.0